ros2_control:
  ros__parameters:
    name: AFDHWSystem
    type: system
    hardware:
      plugin: "afd_hw/AFDHW"
      parameters:
        simulation: "true"
        ip: "192.168.0.12"   # Dummy IP for simulation
        port: "1993"         # Dummy port for simulation
